# Generated by Django 3.0.8 on 2020-09-20 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('male', 'Ανδρικό'), ('female', 'Γύναικείο'), ('child', 'Παιδικό')], max_length=6)),
                ('season', models.CharField(choices=[('winter', 'Χειμωνιάτικο'), ('summer', 'Καλοκαιρινό'), ('spring', 'Mid-season')], max_length=6)),
                ('color', models.CharField(blank=True, max_length=255, null=True)),
                ('size', models.CharField(blank=True, max_length=255, null=True)),
                ('quality', models.CharField(blank=True, max_length=255, null=True)),
                ('brand', models.CharField(blank=True, max_length=255, null=True)),
                ('image_1', models.FileField(upload_to='products/')),
                ('image_2', models.FileField(upload_to='products/')),
                ('image_3', models.FileField(upload_to='products/')),
                ('date_of_arrival', models.DateField()),
                ('sold_out', models.BooleanField(default=False)),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='inventory.Type')),
            ],
        ),
    ]
