# Generated by Django 3.0.8 on 2020-09-20 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20200921_0011'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='sold_out',
            new_name='in_stock',
        ),
    ]
