# Generated by Django 3.0.4 on 2020-03-18 00:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodCombination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=3, max_digits=99999)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=99999)),
                ('measure_unit', models.CharField(choices=[('g', 'grams'), ('ml', 'ml')], max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='FoodCombinationThrough',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=99999)),
                ('food_combination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='money2food.FoodCombination')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='money2food.Ingredient')),
            ],
        ),
        migrations.AddField(
            model_name='foodcombination',
            name='ingredients',
            field=models.ManyToManyField(through='money2food.FoodCombinationThrough', to='money2food.Ingredient'),
        ),
    ]
