# Generated by Django 3.0.4 on 2020-03-18 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money2food', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodcombinationthrough',
            name='quantity',
            field=models.DecimalField(decimal_places=3, max_digits=99999),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=99999),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='quantity',
            field=models.DecimalField(decimal_places=3, max_digits=99999),
        ),
    ]
