# Generated by Django 3.0.4 on 2020-03-18 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money2food', '0002_auto_20200318_0208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='measure_unit',
            field=models.CharField(choices=[('g', 'gram(s)'), ('ml', 'ml(s)'), ('pcs', 'piece(s)')], max_length=8),
        ),
    ]
