# Generated by Django 3.0.4 on 2020-03-21 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money2food', '0005_auto_20200321_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodcombinationthrough',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
